// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mcp

import (
	"encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTool creates a new instance of MockTool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTool {
	mock := &MockTool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTool is an autogenerated mock type for the Tool type
type MockTool struct {
	mock.Mock
}

type MockTool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTool) EXPECT() *MockTool_Expecter {
	return &MockTool_Expecter{mock: &_m.Mock}
}

// Description provides a mock function for the type MockTool
func (_mock *MockTool) Description() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTool_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type MockTool_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *MockTool_Expecter) Description() *MockTool_Description_Call {
	return &MockTool_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *MockTool_Description_Call) Run(run func()) *MockTool_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTool_Description_Call) Return(s string) *MockTool_Description_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTool_Description_Call) RunAndReturn(run func() string) *MockTool_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type MockTool
func (_mock *MockTool) Execute(params json.RawMessage) (string, error) {
	ret := _mock.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(json.RawMessage) (string, error)); ok {
		return returnFunc(params)
	}
	if returnFunc, ok := ret.Get(0).(func(json.RawMessage) string); ok {
		r0 = returnFunc(params)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(json.RawMessage) error); ok {
		r1 = returnFunc(params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTool_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTool_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - params json.RawMessage
func (_e *MockTool_Expecter) Execute(params interface{}) *MockTool_Execute_Call {
	return &MockTool_Execute_Call{Call: _e.mock.On("Execute", params)}
}

func (_c *MockTool_Execute_Call) Run(run func(params json.RawMessage)) *MockTool_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 json.RawMessage
		if args[0] != nil {
			arg0 = args[0].(json.RawMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTool_Execute_Call) Return(s string, err error) *MockTool_Execute_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTool_Execute_Call) RunAndReturn(run func(params json.RawMessage) (string, error)) *MockTool_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// InputSchema provides a mock function for the type MockTool
func (_mock *MockTool) InputSchema() InputSchema {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InputSchema")
	}

	var r0 InputSchema
	if returnFunc, ok := ret.Get(0).(func() InputSchema); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(InputSchema)
	}
	return r0
}

// MockTool_InputSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InputSchema'
type MockTool_InputSchema_Call struct {
	*mock.Call
}

// InputSchema is a helper method to define mock.On call
func (_e *MockTool_Expecter) InputSchema() *MockTool_InputSchema_Call {
	return &MockTool_InputSchema_Call{Call: _e.mock.On("InputSchema")}
}

func (_c *MockTool_InputSchema_Call) Run(run func()) *MockTool_InputSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTool_InputSchema_Call) Return(inputSchema InputSchema) *MockTool_InputSchema_Call {
	_c.Call.Return(inputSchema)
	return _c
}

func (_c *MockTool_InputSchema_Call) RunAndReturn(run func() InputSchema) *MockTool_InputSchema_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockTool
func (_mock *MockTool) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTool_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockTool_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockTool_Expecter) Name() *MockTool_Name_Call {
	return &MockTool_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockTool_Name_Call) Run(run func()) *MockTool_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTool_Name_Call) Return(s string) *MockTool_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTool_Name_Call) RunAndReturn(run func() string) *MockTool_Name_Call {
	_c.Call.Return(run)
	return _c
}
