// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package k8s

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/dynamic"
)

// newMockdynamicClient creates a new instance of mockdynamicClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdynamicClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdynamicClient {
	mock := &mockdynamicClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdynamicClient is an autogenerated mock type for the dynamicClient type
type mockdynamicClient struct {
	mock.Mock
}

type mockdynamicClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdynamicClient) EXPECT() *mockdynamicClient_Expecter {
	return &mockdynamicClient_Expecter{mock: &_m.Mock}
}

// Resource provides a mock function for the type mockdynamicClient
func (_mock *mockdynamicClient) Resource(gvr schema.GroupVersionResource) dynamic.NamespaceableResourceInterface {
	ret := _mock.Called(gvr)

	if len(ret) == 0 {
		panic("no return value specified for Resource")
	}

	var r0 dynamic.NamespaceableResourceInterface
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) dynamic.NamespaceableResourceInterface); ok {
		r0 = returnFunc(gvr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dynamic.NamespaceableResourceInterface)
		}
	}
	return r0
}

// mockdynamicClient_Resource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resource'
type mockdynamicClient_Resource_Call struct {
	*mock.Call
}

// Resource is a helper method to define mock.On call
//   - gvr schema.GroupVersionResource
func (_e *mockdynamicClient_Expecter) Resource(gvr interface{}) *mockdynamicClient_Resource_Call {
	return &mockdynamicClient_Resource_Call{Call: _e.mock.On("Resource", gvr)}
}

func (_c *mockdynamicClient_Resource_Call) Run(run func(gvr schema.GroupVersionResource)) *mockdynamicClient_Resource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.GroupVersionResource
		if args[0] != nil {
			arg0 = args[0].(schema.GroupVersionResource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdynamicClient_Resource_Call) Return(namespaceableResourceInterface dynamic.NamespaceableResourceInterface) *mockdynamicClient_Resource_Call {
	_c.Call.Return(namespaceableResourceInterface)
	return _c
}

func (_c *mockdynamicClient_Resource_Call) RunAndReturn(run func(gvr schema.GroupVersionResource) dynamic.NamespaceableResourceInterface) *mockdynamicClient_Resource_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdiscoveryClient creates a new instance of mockdiscoveryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdiscoveryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdiscoveryClient {
	mock := &mockdiscoveryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdiscoveryClient is an autogenerated mock type for the discoveryClient type
type mockdiscoveryClient struct {
	mock.Mock
}

type mockdiscoveryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdiscoveryClient) EXPECT() *mockdiscoveryClient_Expecter {
	return &mockdiscoveryClient_Expecter{mock: &_m.Mock}
}

// ServerPreferredResources provides a mock function for the type mockdiscoveryClient
func (_mock *mockdiscoveryClient) ServerPreferredResources() ([]*v1.APIResourceList, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerPreferredResources")
	}

	var r0 []*v1.APIResourceList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*v1.APIResourceList, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*v1.APIResourceList); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.APIResourceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdiscoveryClient_ServerPreferredResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerPreferredResources'
type mockdiscoveryClient_ServerPreferredResources_Call struct {
	*mock.Call
}

// ServerPreferredResources is a helper method to define mock.On call
func (_e *mockdiscoveryClient_Expecter) ServerPreferredResources() *mockdiscoveryClient_ServerPreferredResources_Call {
	return &mockdiscoveryClient_ServerPreferredResources_Call{Call: _e.mock.On("ServerPreferredResources")}
}

func (_c *mockdiscoveryClient_ServerPreferredResources_Call) Run(run func()) *mockdiscoveryClient_ServerPreferredResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockdiscoveryClient_ServerPreferredResources_Call) Return(aPIResourceLists []*v1.APIResourceList, err error) *mockdiscoveryClient_ServerPreferredResources_Call {
	_c.Call.Return(aPIResourceLists, err)
	return _c
}

func (_c *mockdiscoveryClient_ServerPreferredResources_Call) RunAndReturn(run func() ([]*v1.APIResourceList, error)) *mockdiscoveryClient_ServerPreferredResources_Call {
	_c.Call.Return(run)
	return _c
}

// newMockrestMapper creates a new instance of mockrestMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockrestMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockrestMapper {
	mock := &mockrestMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockrestMapper is an autogenerated mock type for the restMapper type
type mockrestMapper struct {
	mock.Mock
}

type mockrestMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *mockrestMapper) EXPECT() *mockrestMapper_Expecter {
	return &mockrestMapper_Expecter{mock: &_m.Mock}
}

// KindsFor provides a mock function for the type mockrestMapper
func (_mock *mockrestMapper) KindsFor(input schema.GroupVersionResource) ([]schema.GroupVersionKind, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for KindsFor")
	}

	var r0 []schema.GroupVersionKind
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) ([]schema.GroupVersionKind, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) []schema.GroupVersionKind); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]schema.GroupVersionKind)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(schema.GroupVersionResource) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrestMapper_KindsFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KindsFor'
type mockrestMapper_KindsFor_Call struct {
	*mock.Call
}

// KindsFor is a helper method to define mock.On call
//   - input schema.GroupVersionResource
func (_e *mockrestMapper_Expecter) KindsFor(input interface{}) *mockrestMapper_KindsFor_Call {
	return &mockrestMapper_KindsFor_Call{Call: _e.mock.On("KindsFor", input)}
}

func (_c *mockrestMapper_KindsFor_Call) Run(run func(input schema.GroupVersionResource)) *mockrestMapper_KindsFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.GroupVersionResource
		if args[0] != nil {
			arg0 = args[0].(schema.GroupVersionResource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockrestMapper_KindsFor_Call) Return(groupVersionKinds []schema.GroupVersionKind, err error) *mockrestMapper_KindsFor_Call {
	_c.Call.Return(groupVersionKinds, err)
	return _c
}

func (_c *mockrestMapper_KindsFor_Call) RunAndReturn(run func(input schema.GroupVersionResource) ([]schema.GroupVersionKind, error)) *mockrestMapper_KindsFor_Call {
	_c.Call.Return(run)
	return _c
}

// RESTMapping provides a mock function for the type mockrestMapper
func (_mock *mockrestMapper) RESTMapping(gk schema.GroupKind, versions ...string) (*meta.RESTMapping, error) {
	var tmpRet mock.Arguments
	if len(versions) > 0 {
		tmpRet = _mock.Called(gk, versions)
	} else {
		tmpRet = _mock.Called(gk)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RESTMapping")
	}

	var r0 *meta.RESTMapping
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(schema.GroupKind, ...string) (*meta.RESTMapping, error)); ok {
		return returnFunc(gk, versions...)
	}
	if returnFunc, ok := ret.Get(0).(func(schema.GroupKind, ...string) *meta.RESTMapping); ok {
		r0 = returnFunc(gk, versions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.RESTMapping)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(schema.GroupKind, ...string) error); ok {
		r1 = returnFunc(gk, versions...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrestMapper_RESTMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTMapping'
type mockrestMapper_RESTMapping_Call struct {
	*mock.Call
}

// RESTMapping is a helper method to define mock.On call
//   - gk schema.GroupKind
//   - versions ...string
func (_e *mockrestMapper_Expecter) RESTMapping(gk interface{}, versions ...interface{}) *mockrestMapper_RESTMapping_Call {
	return &mockrestMapper_RESTMapping_Call{Call: _e.mock.On("RESTMapping",
		append([]interface{}{gk}, versions...)...)}
}

func (_c *mockrestMapper_RESTMapping_Call) Run(run func(gk schema.GroupKind, versions ...string)) *mockrestMapper_RESTMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.GroupKind
		if args[0] != nil {
			arg0 = args[0].(schema.GroupKind)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *mockrestMapper_RESTMapping_Call) Return(rESTMapping *meta.RESTMapping, err error) *mockrestMapper_RESTMapping_Call {
	_c.Call.Return(rESTMapping, err)
	return _c
}

func (_c *mockrestMapper_RESTMapping_Call) RunAndReturn(run func(gk schema.GroupKind, versions ...string) (*meta.RESTMapping, error)) *mockrestMapper_RESTMapping_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceFor provides a mock function for the type mockrestMapper
func (_mock *mockrestMapper) ResourceFor(input schema.GroupVersionResource) (schema.GroupVersionResource, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ResourceFor")
	}

	var r0 schema.GroupVersionResource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) (schema.GroupVersionResource, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) schema.GroupVersionResource); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Get(0).(schema.GroupVersionResource)
	}
	if returnFunc, ok := ret.Get(1).(func(schema.GroupVersionResource) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrestMapper_ResourceFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceFor'
type mockrestMapper_ResourceFor_Call struct {
	*mock.Call
}

// ResourceFor is a helper method to define mock.On call
//   - input schema.GroupVersionResource
func (_e *mockrestMapper_Expecter) ResourceFor(input interface{}) *mockrestMapper_ResourceFor_Call {
	return &mockrestMapper_ResourceFor_Call{Call: _e.mock.On("ResourceFor", input)}
}

func (_c *mockrestMapper_ResourceFor_Call) Run(run func(input schema.GroupVersionResource)) *mockrestMapper_ResourceFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.GroupVersionResource
		if args[0] != nil {
			arg0 = args[0].(schema.GroupVersionResource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockrestMapper_ResourceFor_Call) Return(groupVersionResource schema.GroupVersionResource, err error) *mockrestMapper_ResourceFor_Call {
	_c.Call.Return(groupVersionResource, err)
	return _c
}

func (_c *mockrestMapper_ResourceFor_Call) RunAndReturn(run func(input schema.GroupVersionResource) (schema.GroupVersionResource, error)) *mockrestMapper_ResourceFor_Call {
	_c.Call.Return(run)
	return _c
}
